// This file was automatically generated by the GLD.GBES.Product T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `DB_connectionString`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `Data Source=139.155.18.59;Initial Catalog=MEET;Persist Security Info=True;User ID=sa;Password=Chao123`
//     Include Views:          `True`

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace MeettingEasy.Model
{
    /// <summary>
    /// A class which represents the Dic table.
    /// </summary>
	[Table("Dic")]
	public partial class Dic
	{
		public virtual string ID { get; set; }
		public virtual string Text { get; set; }
		public virtual string Type { get; set; }
		public virtual string Notes { get; set; }
	}

    /// <summary>
    /// A class which represents the RegistInfo table.
    /// </summary>
	[Table("RegistInfo")]
	public partial class RegistInfo
	{
		public virtual string ID { get; set; }
		public virtual string Title { get; set; }
		public virtual int Rid { get; set; }
		public virtual DateTime Regdt_begin { get; set; }
		public virtual DateTime Regdt_end { get; set; }
		public virtual string Status { get; set; }
		public virtual string Type { get; set; }
		public virtual DateTime CreateTime { get; set; }
		public virtual int? EnroledCount { get; set; }
		public virtual string Reason { get; set; }
	}

    /// <summary>
    /// A class which represents the Enrol table.
    /// </summary>
	[Table("Enrol")]
	public partial class Enrol
	{
		public virtual int Rid { get; set; }
		public virtual int Oid { get; set; }
		public virtual string Type { get; set; }
		public virtual string Value { get; set; }
	}

    /// <summary>
    /// A class which represents the UserInfo table.
    /// </summary>
	[Table("UserInfo")]
	public partial class UserInfo
	{
		public virtual string ID { get; set; }
		public virtual string Name { get; set; }
		public virtual string Roles { get; set; }
		public virtual string Tel { get; set; }
		public virtual int? Oid { get; set; }
		public virtual string Pwd { get; set; }
	}

    /// <summary>
    /// A class which represents the RegistList view.
    /// </summary>
	[Table("RegistList")]
	public partial class RegistList
	{
		public virtual string ID { get; set; }
		public virtual string Title { get; set; }
		public virtual string Name { get; set; }
		public virtual DateTime Regdt_begin { get; set; }
		public virtual DateTime Regdt_end { get; set; }
		public virtual string Status { get; set; }
		public virtual DateTime CreateTime { get; set; }
		public virtual int? EnroledCount { get; set; }
	}

	/// <summary>
	/// A class which represents the RegistDetail view.
	/// </summary>
	[Table("RegistDetail")]
	public partial class RegistDetail
	{
		public virtual string ID { get; set; }
		public virtual string Title { get; set; }
		public virtual DateTime Regdt_begin { get; set; }
		public virtual DateTime Regdt_end { get; set; }
		public virtual string Type { get; set; }
		public virtual string Name { get; set; }
		public virtual string ServiceIDs { get; set; }
		public virtual string ProtectIDs { get; set; }		
		public virtual int EnroledCount { get; set; }
		public virtual string Reason { get; set; }

	}
    /// <summary>
    /// A class which represents the Org table.
    /// </summary>
	[Table("Org")]
	public partial class Org
	{
		[Key]
		public virtual int ID { get; set; }
		public virtual string Name { get; set; }
		public virtual int? Pid { get; set; }
		public virtual int? Sort { get; set; }
	}

    /// <summary>
    /// A class which represents the Room table.
    /// </summary>
	[Table("Room")]
	public partial class Room
	{
		[Key]
		public virtual int ID { get; set; }
		public virtual string Name { get; set; }
		public virtual string Addres { get; set; }
		public virtual int? Capacity { get; set; }
		public virtual string Facility { get; set; }
		public virtual string Type { get; set; }
		public virtual int? Orgid { get; set; }
		public virtual string ServiceIDs { get; set; }
		public virtual string ProtectIDs { get; set; }
	}

}
